[package]
name = "beancount-plaid"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
chrono = "0.4.38"
env_logger = "0.11.5"
log = "0.4.22"
open = "5.3.1"
plaid = "8.0.0"
rocket = "0.5.1"
tokio = "1.41.1"
